
import ClientOnly from "./componets/ClientOnly";
import Navbar from "./componets/navbar/Navbar";
import RegisterModel from './componets/models/RegisterModel'
import "./globals.css";
import { Nunito } from "next/font/google";
import ToastProvider from "./providers/ToasterProvider";
import LoginModel from "./componets/models/LogoinModel";
import getCurrentUser from "./action/getCurrentUser";
import RentModel from "./componets/models/RentModel";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Journey",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToastProvider />
          <RentModel />
          <LoginModel />
          <RegisterModel />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        {/* {children} */}
      </body>
    </html>
  );
}
